MyExpenses/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using MyExpenses.Data;
using MyExpenses.Models;
using Npgsql;

namespace MyExpenses.Controllers
{
    public class DashboardController : Controller
    {
        private readonly AppDbContext _db;
        private readonly IConfiguration _configuration;

        public DashboardController(AppDbContext _PrAppDbContext, IConfiguration _PrIconfiguration)
        {
            _db = _PrAppDbContext;
            _configuration = _PrIconfiguration;
        }
        public IActionResult Index()
        {
            string connectionString = _configuration.GetConnectionString("connString");
            List<DashboardExpenses> obj = new List<DashboardExpenses>();

            //using (SqlConnection conn = new SqlConnection(connectionString))
            //{
            //    try
            //    {
            //        conn.Open();
            //        string query = "EXEC usp_get_history_dashboard";

            //        using (SqlCommand cmd = new SqlCommand(query, conn))
            //        {
            //            using (SqlDataReader reader = cmd.ExecuteReader())
            //            {
            //                while (reader.Read())
            //                {
            //                    DashboardExpenses readObj = new DashboardExpenses
            //                    {
            //                        Id = Convert.ToInt32(reader["Id"]),
            //                        CategoryName = reader["CategoryName"].ToString(),
            //                        Money = Convert.ToInt32(reader["Money"])
            //                    };
            //                    obj.Add(readObj);
            //                }
            //            }
            //        }
            //        conn.Close();
            //    }
            //    catch (Exception ex)
            //    {
            //        return NotFound();
            //    }


            //}

            using (NpgsqlConnection conn = new NpgsqlConnection(connectionString))
            {
                try
                {
                    conn.Open();
                    string currSchema = "vijay";
                    string query = "SELECT * FROM fn_get_history_dashboard(@schemaName);";

                    using (NpgsqlCommand cmd = new NpgsqlCommand(query, conn))
                    {

                        cmd.Parameters.AddWithValue("schemaName", currSchema);

                        using (NpgsqlDataReader reader = cmd.ExecuteReader())
                        {
                            while (reader.Read())
                            {
                                DashboardExpenses readObj = new DashboardExpenses
                                {
                                    Id = Convert.ToInt32(reader["id"]),
                                    CategoryName = reader["categoryName"].ToString(),
                                    Money = Convert.ToInt32(reader["money"])
                                };
                                obj.Add(readObj);
                            }
                        }
                    }
                    conn.Close();
                }
                catch (Exception ex)
                {
                    return NotFound();
                }


            }
            _db.SaveChanges();
            return View(obj);
        }
    }
}

MyExpenses/Controllers/ExpensesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using Microsoft.JSInterop.Implementation;
using MyExpenses.Data;
using MyExpenses.Models;
using Npgsql;
using NpgsqlTypes;
using System.Data;

namespace MyExpenses.Controllers
{
    public class ExpensesController : Controller
    {
        private readonly AppDbContext _db;
        private readonly IConfiguration _configuration;

        public ExpensesController(AppDbContext _PrAppDbContext, IConfiguration _prIconfiguration)
        {
            _db = _PrAppDbContext;
            _configuration = _prIconfiguration;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Create()
        {

            return View();
        }
        [HttpPost]
        public IActionResult Create(Expenses obj)
        {
            string objDateStr = obj.Date.ToShortDateString();
            int objDateInt = Convert.ToInt32(objDateStr.Substring(0, 2));
            string objMonthStr = obj.Date.ToShortDateString();
            int objMonthInt = Convert.ToInt32(objMonthStr.Substring(3, 2));
            string objYearStr = obj.Date.ToShortDateString();
            int objYearInt = Convert.ToInt32(objYearStr.Substring(6, 4));

            string connectionString = _configuration.GetConnectionString("connstring");
            
            List<Expenses> list = new List<Expenses>();

            //using (SqlConnection conn = new SqlConnection(connectionString))
            //{
            //    try
            //    {
            //        conn.Open();

            //        string currSchema = "vijay";
            //        //string query1 = "EXEC usp_add_expenses @Category = @Category, @Name = @Name, @Location = @Location, @Year = @Year, @Month = @Month, @Date = @Date, @Money = @Money";
            //        string query = "SELECT fn_add_expenses(@SchemaName, @Category::INTEGER, @Name, @Location, @Year::SMALLINT, @Month::SMALLINT, @Date::TIMESTAMP, @Money::INTEGER)";

            //        using (SqlCommand cmd = new SqlCommand(query, conn))
            //        {
            //            cmd.Parameters.AddWithValue("@SchemaName", currSchema);
            //            cmd.Parameters.AddWithValue("@Category", obj.Category);
            //            cmd.Parameters.AddWithValue("@Name", obj.Name);
            //            cmd.Parameters.AddWithValue("@Location", obj.Location);
            //            cmd.Parameters.AddWithValue("@Year", objYearInt);
            //            cmd.Parameters.AddWithValue("@Month", objMonthInt);
            //            cmd.Parameters.AddWithValue("@Date", obj.Date);
            //            cmd.Parameters.AddWithValue("@Money", obj.Money);

            //            int rowsAffected = cmd.ExecuteNonQuery();
            //            if (rowsAffected > 0)
            //            {
            //                conn.Close();
            //                TempData["Success"] = "Expenses Created Successfully";
            //            }
            //            else
            //            {
            //                conn.Close();
            //                return NotFound();
            //            }
            //        }
            //    }
            //    catch (Exception ex)
            //    {
            //        return NotFound();
            //    }
            //}


            using (NpgsqlConnection conn = new NpgsqlConnection(connectionString))
            {
                try
                {
                    conn.Open();

                    string currSchema = "vijay";
                    string query = "SELECT fn_add_expenses(@SchemaName, @Category, @Name, @Location, @Year, @Month, @Date, @Money)";

                    using (NpgsqlCommand cmd = new NpgsqlCommand(query, conn))
                    {
                        cmd.Parameters.AddWithValue("SchemaName", currSchema).NpgsqlDbType = NpgsqlDbType.Text;
                        cmd.Parameters.AddWithValue("Category", obj.Category).NpgsqlDbType = NpgsqlDbType.Integer;
                        cmd.Parameters.AddWithValue("Name", obj.Name).NpgsqlDbType = NpgsqlDbType.Text;
                        cmd.Parameters.AddWithValue("Location", obj.Location).NpgsqlDbType = NpgsqlDbType.Text;
                        cmd.Parameters.AddWithValue("Year", objYearInt).NpgsqlDbType = NpgsqlDbType.Smallint;
                        cmd.Parameters.AddWithValue("Month", 11).NpgsqlDbType = NpgsqlDbType.Smallint;
                        cmd.Parameters.AddWithValue("Date", obj.Date).NpgsqlDbType = NpgsqlDbType.Timestamp;
                        cmd.Parameters.AddWithValue("Money", obj.Money).NpgsqlDbType = NpgsqlDbType.Integer;

                        cmd.ExecuteNonQuery();

                        conn.Close();
                        TempData["Success"] = "Expenses Created Successfully";
                    }
                }
                catch (Exception ex)
                {
                    TempData["Error"] = "Expenses Created Failed";

                }
                finally
                {
                    if (conn.State == ConnectionState.Open)
                    {
                        conn.Close();
                    }
                }

            }


            return RedirectToAction("Index","Home");
        }

        public IActionResult Edit()
        {
            return View();
        }

        public IActionResult Delete()
        {
            return View();
        }
    }
}

MyExpenses/Views/Shared/_Forms.cshtml
<h2>Forms</h2>

MyExpenses/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyExpenses</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MyExpenses.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark">
        <div class="container-fluid">
            <a class="navbar-brand text-white" asp-controller="Home" asp-action="Home">MyExpenses</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarColor01">
                <ul class="navbar-nav me-auto">
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Home" asp-action="Index">
                            Home
                            <span class="visually-hidden">(current)</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Expenses" asp-action="Create">New Expenses</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="History" asp-action="Index">History</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Dashboard" asp-action="Index">Dashboard</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Home" asp-action="Index">Logout</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notifications" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MyExpenses - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MyExpenses/Views/Shared/_Notifications.cshtml
@if (TempData["Success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script>
        toastr.success('@TempData["Success"]')
    </script>
    
}

@if (TempData["Error"] !=  null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script>
        toastr.error('@TempData["Error"]')
    </script>
}